-- 코드를 입력하세요
SELECT
    YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    A.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO AS A INNER JOIN ONLINE_SALE AS B
    ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY SUBSTR(B.SALES_DATE, 1, 7), A.GENDER
ORDER BY `YEAR`, `MONTH`, GENDER