-- 코드를 작성해주세요
WITH RECURSIVE Generation AS(
    SELECT ID, PARENT_ID, 1 AS Gen
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.Gen + 1
    FROM ECOLI_DATA AS E
    INNER JOIN Generation G ON G.ID = E.PARENT_ID
)
SELECT 
    COUNT(*) AS `COUNT`,
    Gen AS GENERATION
FROM Generation
WHERE ID NOT IN(
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY Gen
ORDER BY Gen