-- 코드를 작성해주세요
SELECT
    DISTINCT A.ID, 
    A.EMAIL, 
    A.FIRST_NAME, 
    A.LAST_NAME
FROM 
    DEVELOPERS AS A INNER JOIN SKILLCODES AS B
    ON (A.SKILL_CODE & B.CODE) = B.CODE
WHERE B.NAME IN ('Python', 'C#')
ORDER BY ID