SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (SELECT MAX(SIZE_OF_COLONY)
     FROM ECOLI_DATA
     WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(e.DIFFERENTIATION_DATE)
    ) - e.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS e
ORDER BY YEAR, YEAR_DEV 
